kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err
kmergenie data2/Trimmed/TrimmedC2L1R1.fastq -o data2/KmerGenie/histograms > data2/KmerGenie/log.log 2> data2/KmerGenie/err.err

